### ISSUE TITLE
Cannot compile in Linux (Alpine 3.11)

### ISSUE THREAD

**Issue by Auska** [cfpp2p/transmission#13]
System：Alpine 3.11
GCC：9.2.0
When executing `./configure --disable-nls && make install`
```
  CC     inout.o
In file included from inout.c:22:
fdlimit.h:39:51: error: unknown type name 'off_t'
   39 | ssize_t tr_pread(int fd, void *buf, size_t count, off_t offset);
      |                                                   ^~~~~
fdlimit.h:40:58: error: unknown type name 'off_t'
   40 | ssize_t tr_pwrite(int fd, const void *buf, size_t count, off_t offset);
      |                                                          ^~~~~
fdlimit.h:41:25: error: unknown type name 'off_t'
   41 | int tr_prefetch(int fd, off_t offset, size_t count);
      |                         ^~~~~
inout.c: In function 'readOrWriteBytes':
inout.c:172:28: warning: implicit declaration of function 'tr_pread' [-Wimplicit-function-declaration]
  172 |             const int rc = tr_pread( fd, buf, buflen, offset );
      |                            ^~~~~~~~
inout.c:172:28: warning: nested extern declaration of 'tr_pread' [-Wnested-externs]
inout.c:180:28: warning: implicit declaration of function 'tr_pwrite'; did you mean 'tr_ioWrite'? [-Wimplicit-function-declaration]
  180 |             const int rc = tr_pwrite( fd, buf, buflen, offset );
      |                            ^~~~~~~~~
      |                            tr_ioWrite
inout.c:180:28: warning: nested extern declaration of 'tr_pwrite' [-Wnested-externs]
inout.c:216:21: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  216 |                     char * cFilename = tr_buildPath( cBase, cSubpath, NULL );
      |                     ^~~~
inout.c:225:13: warning: implicit declaration of function 'tr_prefetch'; did you mean 'tr_ioPrefetch'? [-Wimplicit-function-declaration]
  225 |             tr_prefetch( fd, offset, buflen );
      |             ^~~~~~~~~~~
      |             tr_ioPrefetch
inout.c:225:13: warning: nested extern declaration of 'tr_prefetch' [-Wnested-externs]
make[1]: *** [Makefile:693: inout.o] Error 1
```
